### ISSUE TITLE
Need some approximate computing resource requirements

### ISSUE THREAD

**Issue by leipzig** [broadinstitute/warp#1037]
https://github.com/broadinstitute/warp/blob/develop/website/docs/About_WARP/PipelineRequirements.md

I realize there is a lot of variation here but this page should probably at least specify some minimum (nodes, disk, cpus) computing resources WARP requires for its plumbing and scientific test sets

**Comment by kevinpalis** [comment]
Hi @leipzig, thanks for the suggestion! We think this is a good idea and we're adding it to our backlog. We'll keep you posted!

**Comment by aawdeh** [comment]
Closing this issue. We are working on incorporating the suggestions.
