### ISSUE TITLE
SumFloats and size function

### ISSUE THREAD

**Issue by shengqh** [broadinstitute/warp#1046]
SunFloats is used in multiple workflow to get the total file size, for example, 

```
SplitLargeReadGroup:
call Utils.SumFloats as SumSplitAlignedSizes
```

```
UnmappedBamToAlignedBam:
call Utils.SumFloats as SumFloats
```

However, when I was running a few thousands WGS single sample workflows at terra, sometimes, it would be idled at calling SumFloats for more than 10 hours. 

I noticed that size function accepting array of file as input parameter. I am wondering why you don't use size function directly?
For example, in UnmappedBamToAlignedBam:

Use

```
Float total_bam_size = size(output_aligned_bam, "GiB")
```

Instead of 

```
  # Sum the read group bam sizes to approximate the aggregated bam size
  call Utils.SumFloats as SumFloats {
    input:
      sizes = mapped_bam_size,
      preemptible_tries = papi_settings.preemptible_tries
  }
```

**Comment by ekiernan** [comment]
We've merged the PR. Closing the issue. Thank you again for the suggestion.
