### ISSUE TITLE
Add Ultima Single Sample outputs to VerifyNA12878 tests

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/warp#1154]
We expect small changes in the Ultima single sample pipelines when updating versions of software because there is a filtering method applied that uses a random seed (which fills in the `TREE_SCORE` annotation and provides the single sample filtered VCF). It would be helpful for future updates if we could include the NA12878 used for the Scientific Tests in the VerifyNA12878 tests to make the decision to update or not easier.

**Comment by jessicaway** [comment]
@mshand would you still like to see this update?

**Comment by meganshand** [comment]
I still think this feature should happen at some point. It's most valuable the next time we change the single sample pipeline such that we need to evaluate the scientific tests, so the urgency could be calibrated around when we expect another batch of changes (I don't know of any coming in the near future).

**Comment by jessicaway** [comment]
Thank you! We'll keep this open

**Comment by meganshand** [comment]
Actually, I think this may be done: https://github.com/broadinstitute/warp/blob/develop/verification/VerifyUltimaGenomicsWholeGenomeGermline.wdl#L112

I think we snuck this into the GATK 4.6.0.0 update. Sorry for the confusion!
