### ISSUE TITLE
Requesting your feedback on community discussion

### ISSUE THREAD

**Issue by claymcleod** [broadinstitute/warp#1264]
Hi there,

We're building some community tooling around WDL at @stjude-rust-labs in the [`wdl`](https://github.com/stjude-rust-labs/wdl) project, and we've identified this repository as one containing quite a bit of WDL workflows. In turn, we're assuming you have quite a bit of experience with WDL and may have opinions on how to best write it. We hope that you'll participate in this discussion (https://github.com/stjude-rust-labs/wdl/discussions/17) so that we can ultimately build tools that improve the WDL community.

Though not ideal, we're reaching out via an issue when there is no clear individual or email to contact to request participation. To that end, feel free to close and/or archive this issue at any time.

**Comment by ekiernan** [comment]
Hi @claymcleod, we've written a few docs on WDL best practices that you are welcome to reuse. Most of them are based on our experience running WDL on Google Cloud backend, but we are currently updating materials for Azure as well. 

You can find some best practices docs in our WARP docs here: https://broadinstitute.github.io/warp/docs/get-started

And we have contribute to wdl-docs community here: https://docs.openwdl.org/en/latest/

We hope that's helpful.
