### ISSUE TITLE
Missing BAM indexes causes pipeline failure during sharded BQSR

### ISSUE THREAD

**Issue by bshifaw** [broadinstitute/warp#129]
From pull request in the gatk-workflows org [here](https://github.com/gatk-workflows/gatk4-exome-analysis-pipeline/pull/18). The exome pipeline lacks index variables for some of the bam files causing it to fail on Singularity backend. Adding an index file along with the BAM file will fix the issue

> Issue first reported by Umang here: https://gatk.broadinstitute.org/hc/en-us/community/posts/360068718312-issue-with-gatk4-exome-analysis-pipeline-when-running-given-sample-data
> 
> Reproduced in the following environment:
> 
> - Cromwell 52 (listed as supported)
> - gatk-workflows/gatk4-exome-analysis-pipeline 1.4.0 release
> - Singularity backend from example
>   - https://github.com/broadinstitute/cromwell/blob/develop/cromwell.example.backends/singularity.conf

**Comment by exander77** [comment]
Can confirm.
Seems like there is a missing code in SortSam:
` samtools index ~{output_bam_basename}.bam ~{output_bam_basename}.bai`

**Comment by exander77** [comment]
And the index needs to be passed around as well.

**Comment by exander77** [comment]
Seems some tools call is not needed, just to pass indexes around.

**Comment by exander77** [comment]
Why is this not fixed? I used a fix from @bshifaw. It works and I suggest pulling it.

**Comment by sophiacrennan** [comment]
I have created a PR for the fix [here](https://github.com/broadinstitute/warp/pull/179). Since the PR is slightly different than the PR made in gatk-workflows, I've been trying to set up singularity on my computer to test it out but I am having difficulties. @exander77 would you mind making sure the WARP PR fixes the problem you encountered? If its all good, then I can merge it up.

**Comment by exander77** [comment]
@sophiacrennan I have it working fine, so I can make a PR. I updated to head of developed:
https://github.com/broadinstitute/warp/pull/189/commits

**Comment by kbergin** [comment]
This has been resolved and merged in https://github.com/broadinstitute/warp/pull/179
