### ISSUE TITLE
workflow request: demultiplexing using picard

### ISSUE THREAD

**Issue by matthdsm** [broadinstitute/warp#131]
Hi,

I don't know if there's a lot of interest from the community for this, but I'm wondering if you could put up your take on a demultiplexing workflow?

We're currently developing this on our own, but it'd be great to learn from the masters so we get it right from the get go.

Thanks
M

**Comment by kbergin** [comment]
Hi @matthdsm - I apologize I didn't see this issue sooner. We currently do our demultiplexing in an on prem legacy system, so we don't have a cloud workflow yet. However, a collaborator uses this workflow for demultiplexing, I hope it helps! https://dockstore.org/workflows/github.com/broadinstitute/viral-pipelines/demux_only:master?tab=info

**Comment by matthdsm** [comment]
wow, this is great, thanks!

M

**Comment by kbergin** [comment]
Just wanted to extend that thanks to @dpark01 - Thank you, Danny, for creating public resources for the WDL community!
