### ISSUE TITLE
calculate_cost.py failed -- The dictionary doesn't contain a US cost object

### ISSUE THREAD

**Issue by nicholema** [broadinstitute/warp#1381]
Hi, I was using calculate_cost.py to calculate cost for our wdl workflow. 
I output metadata using instructions on AoU example notebook and run the script with

```
cromshell -t 200 -q metadata {id} > metadata.colored.json
sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g' metadata.colored.json > metadata.json
python calculate_cost.py -m  metadata.json  | cut -f 1,3-6,25 | column -t -s $'\t' > costs.tsv
```
it failed and has error msg 

> The dictionary doesn't contain a US cost object

Do you have any insight on what is going on? I am also running within US

**Comment by jessicaway** [comment]
Hi @nicholema, 
The calculate_cost.py script is unfortunately out of date and known to be inaccurate (especially is custom machines are used within a workflow). We recommend following the steps listed in [this article](https://support.terra.bio/hc/en-us/articles/7671288432667-Workflows-cost-estimating-notebook#h_01J3QM5KJ0SD3JW8RR7PJ7J9NP) to get a cost estimation for a workflow. 
Sorry for the confusion! We will make this script as deprecated
