### ISSUE TITLE
Provide public WholeGenomeGermlineSingleSample input files

### ISSUE THREAD

**Issue by johnbradley** [broadinstitute/warp#1417]
This input json file references two files that are in a private bucket:
https://github.com/broadinstitute/warp/blob/599f119c0220930bca8667bb7539d4bf81edcf06/pipelines/broad/dna_seq/germline/single_sample/wgs/input_files/WholeGenomeGermlineSingleSample.inputs.plumbing.masked_reference.json#L50-L51

Is there a public source for these files?

**Comment by jessicaway** [comment]
Hi @johnbradley, 

These are optional files, you can simply remove them from the inputs. If you would like public data for this pipeline it is available in this workspace: https://app.terra.bio/#workspaces/warp-pipelines/Whole-Genome-Analysis-Pipeline

Hope that helps!
