### ISSUE TITLE
Wrong import path...

### ISSUE THREAD

**Issue by exander77** [broadinstitute/warp#156]
Why is this project so riddled with bugs?
```
--- a/tasks/broad/Alignment.wdl
+++ b/tasks/broad/Alignment.wdl
@@ -15,7 +15,7 @@ version 1.0
 ## page at https://hub.docker.com/r/broadinstitute/genomes-in-the-cloud/ for detailed
 ## licensing information pertaining to the included programs.
 
-import "../structs/dna_seq/DNASeqStructs.wdl"
+import "../../structs/dna_seq/DNASeqStructs.wdl"
```

**Comment by kbergin** [comment]
Hi @exander77 thank you for filing this bug! I'm sorry I didn't see the issue sooner. We will work on fixing this asap, and early in the new year we will install a wdl validator to avoid bugs like this in the future. Our tests flatten the imports before running, so they didn't catch this.

**Comment by jennydaman** [comment]
Is it possible for the patch to be backported to the `ExomeGermlineSingleSample_v2.2.0` tag? Currently this bug prevents it from being imported into Terra.

**Comment by kbergin** [comment]
This will be fixed in https://github.com/broadinstitute/warp/pull/172 and released to dev soon. We'll then work on cutting official releases, which will be minor or patch bumps to the version numbers depending on the workflow. I will follow up here when these are on develop, released, and in Terra.

**Comment by exander77** [comment]
I have fixed it in my code and I can try after it is fixed.

**Comment by kbergin** [comment]
Hi all, the latest releases here https://github.com/broadinstitute/warp/releases/tag/WholeGenomeGermlineSingleSample_v2.3.1 and https://github.com/broadinstitute/warp/releases/tag/ExomeGermlineSingleSample_v2.4.1 have this bug fixed. We will push them to Terra soon.
