### ISSUE TITLE
Default reference file

### ISSUE THREAD

**Issue by chadisaad** [broadinstitute/warp#183]
Why using the GRCH38+alt  reference fasta instead of HG38 **analysis set** . Isn't a problem for PAR regions ?

**Comment by kbergin** [comment]
Hi @chadisaad - 

Thanks for your question, apologies for the delay, we were on holiday break! I'm cc'ing in a few folks to help. @yfarjoun @ekiernan would either of you be familiar with this? 

Best,
Kylee

**Comment by yfarjoun** [comment]
At the time, we didn't think of PAR and the advice (from Heng Li)to  the Functional Equivalence group was to use this reference. as we start analysing chrX and chrY, this might be a problem.....

**Comment by kbergin** [comment]
Thank you, Yossi! 

For this time, we will be continuing to adhere to Functional Equivalence (more info here in a [blog post](https://github.com/broadinstitute/gatk-docs/blob/master/blog-2012-to-2019/2018-02-09-Batch_effects_begone:_Introducing_the_Functional_Equivalence_data_processing_pipeline_spec.md), [spec](https://github.com/CCDG/Pipeline-Standardization/blob/master/PipelineStandard.md), [nature paper](https://www.nature.com/articles/s41467-018-06159-4)) for our default. We'll add a bit more information about this standard to our pipeline documentation so this is clearer.

Best,
Kylee
