### ISSUE TITLE
Why is history such a mess?

### ISSUE THREAD

**Issue by exander77** [broadinstitute/warp#198]
![Screenshot_2021-01-11_13-56-31](https://user-images.githubusercontent.com/2256039/104185283-0c291f00-5415-11eb-8723-f7d26f181795.png)

**Comment by gbggrant** [comment]
Hi @exander77 - I'm not familiar with the tool that you are using here.  I generally use github's network tool to inspect history: https://github.com/broadinstitute/warp/network - And as I mentioned in the other issue, looking at the master branch (which is where released pipelines are) is probably more appropriate than develop.

**Comment by exander77** [comment]
@gbggrant This is standard gitk (it is part of the git itself). It is very hard to navigate in the project as branches are merged together a lot. I may try to use the master.
