### ISSUE TITLE
[WholeGenomeGermlineSingleSample] Strange behaviour change after update

### ISSUE THREAD

**Issue by exander77** [broadinstitute/warp#199]
I updated a few days back to the latest `develop`:
Previously, the workflow result was:
`1,5G	sampleA.g.vcf.gz`

Now it is:
`6,7G	sampleB.g.vcf.gz`

It is still running, but 6,7GB seem way too much.

The partial `vcf.gz` files are larger as well.

**Comment by gbggrant** [comment]
HI @exander77 could you give a bit more context about what you are seeing?  What was the previous develop version you were using? (either a commit hash, or a time estimate might help).  We routinely test with a variety of test samples and have not seen significant changes in the outputs recently.
Also, we would recommend you pull the released workflows from: https://github.com/broadinstitute/warp/releases - as expected, workflows on the develop branch are under active development and have not gone through full testing.

**Comment by exander77** [comment]
@gbggrant I checked against the previous version, and nothing seems related.

I am thinking it may be the data. The number of SNPs is similar in both samples, so maybe quality differed widely and regions didn't get merged. But the disparity between those files is huge.

![comparison](https://user-images.githubusercontent.com/2256039/104346104-538bda00-54ff-11eb-854e-b6895de38802.png)

**Comment by kbergin** [comment]
Closing this given it seems like something about the data not the pipeline update. Thanks!
