### ISSUE TITLE
CheckContamination task with NA output

### ISSUE THREAD

**Issue by diegomscoelho** [broadinstitute/warp#203]
Hi there,

I've been using broadinstitute WES genotyping pipeline for a year now. I got an odd problem a few times:

row["FREEMIX"] = NaN in CheckContamination task [here](https://github.com/broadinstitute/warp/blob/5ab83cbc165ec535a7081e907c7dce19136eca10/tasks/broad/BamProcessing.wdl#L487). Basically, `Float contamination = read_float(stdout())` breaks because output is NaN.

PS.: row["FREELK1"] == -0 but row["FREELK0"] != 0.

In both cases, I've subsampled our .bam file and realized that we didn't have a problem with our samples. The rest of genotyping workflow was ok. Our samples were not empty or had an incompatible reference.

I managed this error setting a condition for NaN (`if math.isnan(float(row["FREEMIX"])):`) and printing `-1`. It's pretty rare but it's useful not break pipeline to a possible output.

If you guys prefer, I can add a PR with my code (just 3 lines).

**Comment by kbergin** [comment]
Hi Diego - thank you for filing this issue! I think we've seen this error before as well and I thought we had put in a fix for it - @gbggrant do you recall? 

What version of the pipeline are you using when you see this error?

**Comment by diegomscoelho** [comment]
Hi again,

I'm using this docker image:
us.gcr.io/broad-gotc-prod/verify-bam-id:c8a66425c312e5f8be46ab0c41f8d7a1942b6e16-1500298351
I saw it has two newer docker version in your repo [here](https://console.cloud.google.com/gcr/images/broad-gotc-prod/US/verify-bam-id?gcrImageListsize=30). I will try with this newer version and report if our problem goes away.

**Comment by diegomscoelho** [comment]
Hi @kbergin,

The newest version worked just fine. I only need to add `--DisableSanityCheck`.

Thanks!

**Comment by kbergin** [comment]
Excellent news! We sometimes have to disable sanity check when we run this pipeline in production, though it typically only comes up if the data doesn't have enough coverage over the SNPs used to make the contamination resources.
