### ISSUE TITLE
Remove deprecated Paired_Run arg from MergeBamAlignment

### ISSUE THREAD

**Issue by bshifaw** [broadinstitute/warp#221]
**Problem:**
[MergeBamAlignment](https://github.com/broadinstitute/warp/blob/041a85bf2a3efe2e83f0f7c3bd08d44ebd1866b4/tasks/broad/Alignment.wdl#L83) is using a deprecated argument called `Paired_Run`. Source [forum thread](https://gatk.broadinstitute.org/hc/en-us/community/posts/360076413951-Hg38-RNAseq-germline-variant-calling-BQSR-steps?page=1#community_comment_360014206472).

The `SamToFastqAndBwaMemAndMba` task uses `us.gcr.io/broad-gotc-prod/genomes-in-the-cloud:2.4.7-1603303710`. This docker uses Picard version Version:2.23.8, this version of picard has [deprecated](https://github.com/broadinstitute/picard/blob/4c937e5bb8b790a5b7096c1e61564633e83298f0/src/main/java/picard/sam/MergeBamAlignment.java#L195) the argument Paired_Run for MergeBamAlignment.

**Fix:** 
Remove [Paired_Run](https://github.com/broadinstitute/warp/blob/041a85bf2a3efe2e83f0f7c3bd08d44ebd1866b4/tasks/broad/Alignment.wdl#L83) argument from command

**Comment by kbergin** [comment]
Thank you for filing this, Beri, I'll note this in our backlog.

**Comment by kbergin** [comment]
@kachulis Do you know if we can just remove this parameter without causing any issues? Is there another parameter we're supposed to use instead? This would impact both Genome and Exome pipelines.

**Comment by kachulis** [comment]
@kbergin that argument is completely ignored in the source code, so can safely be removed from the calling tasks.
