### ISSUE TITLE
ExomeGermlineSingleSample_v2.4.1 - docker used in MarkDuplicatesSpark

### ISSUE THREAD

**Issue by ana-stankovic** [broadinstitute/warp#250]
Hello, 
The MarkDuplicatesSpark step in BamProcessing.wdl of the ExomeGermlineSingleSample_v2.4.1 uses the [`jamesemery/gatknightly:gatkMasterSnapshot44ca2e9e84a`](https://hub.docker.com/layers/jamesemery/gatknightly/gatkMasterSnapshot44ca2e9e84a/images/sha256-55d1b4048c812e658a159cf17d20aa095104a5109f12a659c6238542529c621b?context=explore) docker.
This is the only tool that uses this docker, while others are primarily from the `us.gcr.io/broad-gatk` or `us.gcr.io/broad-gotc-prod` repositories. 
Why is this particular docker used, and what toolkit versions are installed inside? Does it correspond to a version from the [`broadinstitute/gatk-nightly`](https://hub.docker.com/r/broadinstitute/gatk-nightly/tags?page=1&ordering=last_updated) repo?

Thank you,
Ana Stankovic

**Comment by gbggrant** [comment]
Hi @ana-stankovic thanks for pointing that out.  I can look into that further, but I'm pretty sure that was a task that was added for testing purposes and hasn't been used / acted upon in a while.  That task is not called in the pipeline.

**Comment by exander77** [comment]
@gbggrant I created a different issue with the question of why is not Spark (or a different parallel implementation) used?
https://github.com/broadinstitute/warp/issues/266
Is there a reason for it? This seems to be a major bottleneck.

**Comment by kbergin** [comment]
Hi @ana-stankovic and @exander77 - I responded regarding MDSpark on #266 . We will clean up this task in BamProcessing for now and consider adding MDSpark for large sample processing in the future. It's likely that it would be most useful for high coverage genomes. At that time we will definitely use the published dockers.
