### ISSUE TITLE
test files inaccessible

### ISSUE THREAD

**Issue by leipzig** [broadinstitute/warp#271]
hi can you either replace these 3 files with open versions (gs://broad-public-datasets seems to have them?) or make them public? thx
https://github.com/broadinstitute/warp/blob/develop/pipelines/broad/dna_seq/germline/single_sample/wgs/input_files/WholeGenomeGermlineSingleSample.inputs.plumbing.json#L6-L8

**Comment by kbergin** [comment]
Hi @leipzig - thanks for pointing this out! We are definitely keen to have all of our test data be public (whenever data permissions allow!). I'm running our tests now to confirm that these are in fact the exact same input files, given they have the same names it seems likely! https://github.com/broadinstitute/warp/pull/272

**Comment by kbergin** [comment]
Hi @leipzig - This specific example has been updated with the close of #272 . It's on develop for now and will make its way up to master soon. 

We will revisit our test inputs in general as well to look for opportunities to use public test data. Thanks for submitting an issue and let us know if you have other feedback!

**Comment by leipzig** [comment]
Hi Kylee,
The call-CheckFingerprint step is trying to fetch:
`gs://broad-gotc-test-storage/single_sample/plumbing/bams/G96830.NA12878/G96830.NA12878.hg38.reference.fingerprint.vcf.gz`

which is also unavailable

**Comment by leipzig** [comment]
I tried to swap in `gs://dsde-data-na12878-public/NA12878.hg38.reference.fingerprint.vcf` from $5 genome but that turned out not to be a great idea as the sample names do not match up

**Comment by kbergin** [comment]
Hi @leipzig -

So our pipeline supports this concept of [fingerprinting](https://gatk.broadinstitute.org/hc/en-us/articles/360041696232-Detecting-sample-swaps-with-Picard-tools), where a user could run an array or sequencing over specific fingerprint snps and then use that to compare to the full sequencing reads and determine if any sample swaps occurred in the lab. I'm not sure how many users have both array and sequencing data over the right regions to use this feature. 

We will work on making the example input json we have functional for users outside of the Broad. We'll make the file public and update the example input json. Thanks for bearing with us.

In the meantime you have two options:
1. you could skip this fingerprinting feature by removing these inputs from the example:
`haplotype_database_file`, `WholeGenomeGermlineSingleSample.fingerprint_genotypes_file`, and `WholeGenomeGermlineSingleSample.fingerprint_genotypes_index`
2. you can use the public test data linked in this [Terra workspace](https://app.terra.bio/#workspaces/warp-pipelines/Whole-Genome-Analysis-Pipeline/data) (it's NA12878) and the file you pointed to (`gs://dsde-data-na12878-public/NA12878.hg38.reference.fingerprint.vcf`). If you go this route and use all 24 of these readgroups, you shouldn't need to do the `disable_sanity_check` for contamination anymore, they should cover enough contamination sites. They've been downsampled very specifically to cover select entire chromosomes, randomly a portion of the whole genome, and specifically the fingerprinting and contamination sites. 

I hope that helps!

**Comment by leipzig** [comment]
Thanks, that did work once i renamed the sample in `gs://dsde-data-na12878-public/NA12878.hg38.reference.fingerprint.vcf` to `NA12878 PLUMBING`

**Comment by mr-c** [comment]
Hello,
I'm trying to reproduce [reprocessing/exome/test_inputs/Plumbing/RP-929.NA12878.json](https://github.com/broadinstitute/warp/blob/8af8bb927a02651bbcecd18542878db856c6dee4/pipelines/broad/reprocessing/exome/test_inputs/Plumbing/RP-929.NA12878.json) locally 
(as I'm trying to derive standalone test data for [CollectReadgroupBamQualityMetrics](https://github.com/broadinstitute/warp/blob/9ea4dc8ad4eca794ed336451fa8b23367132a820/tasks/broad/Qc.wdl#L92))

and I'm unable to download `gs://broad-gotc-test-storage/germline_single_sample/exome/plumbing/bams/RP-929.NA12878/RP-929.NA12878.reference.fingerprint.vcf.gz`

**Comment by kbergin** [comment]
Awesome, thanks for the reminder and for making a ticket- I've prioritized this we should be able to get to it in the next month-ish. And +1 thank you for the contribution!

**Comment by gbggrant** [comment]
The work described in this issue have been represented in a Jira ticket. Closing this issue accordingly.

**Comment by mr-c** [comment]
@gbggrant is this project no longer using GitHub Issues? Is your Jira public?

**Comment by kbergin** [comment]
We use github issues for the public, our organization requires we use our private jira for team backlog management. Let's leave keep this open. 

I'm sorry the PR has lost steam, iirc correctly part of the issue was that the public files that were pointed to in the PR weren't the same test data, but I can't recall for sure.

**Comment by hkeward** [comment]
FYI the fingerprint files are still inaccessible.

[leipzig's fix](https://github.com/broadinstitute/warp/issues/271#issuecomment-829140439) worked for me (renaming the sample in gs://dsde-data-na12878-public/NA12878.hg38.reference.fingerprint.vcf).

**Comment by aawdeh** [comment]
Closing issue as it was resolved.

**Comment by shamardina** [comment]
Hello,

I'm trying to run ExomeGermlineSingleSample locally and wanted to use the plumbing data https://github.com/broadinstitute/warp/blob/develop/pipelines/broad/dna_seq/germline/single_sample/exome/test_inputs/Plumbing/RP-929.NA12878.json for testing.

Thanks to this discussion, I got `gs://broad-references-private/HybSelOligos/whole_exome_illumina_coding_v1/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.targets.interval_list` and `gs://broad-references-private/HybSelOligos/whole_exome_illumina_coding_v1/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.baits.interval_list` from `gs://gcp-public-data--broad-references/hg38/v0/HybSelOligos/whole_exome_illumina_coding_v1/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.targets.interval_list` and `gs://gcp-public-data--broad-references/hg38/v0/HybSelOligos/whole_exome_illumina_coding_v1/whole_exome_illumina_coding_v1.Homo_sapiens_assembly38.baits.interval_list`.

However, I can't find publicly available versions of the input BAM and fingerprint VCF:

* `gs://broad-gotc-test-storage/germline_single_sample/exome/plumbing/bams/RP-929.NA12878/HJ5LVADXX.1.downsampled.unmapped.bam`
* `gs://broad-gotc-test-storage/germline_single_sample/exome/plumbing/bams/RP-929.NA12878/RP-929.NA12878.reference.fingerprint.vcf.gz`
* `gs://broad-gotc-test-storage/germline_single_sample/exome/plumbing/bams/RP-929.NA12878/RP-929.NA12878.reference.fingerprint.vcf.gz.tbi`

Is it possible to make those too publicly available please?
