### ISSUE TITLE
Describe fingerprint_genotypes input in Readme

### ISSUE THREAD

**Issue by bshifaw** [broadinstitute/warp#305]
**Problem** 
The workflow test input for WholeGenomeGermlineSingleSample currently [lists](https://github.com/broadinstitute/warp/blob/20dbe7e7c602c116203523055da3399dbee9b399/pipelines/broad/dna_seq/germline/single_sample/wgs/input_files/WholeGenomeGermlineSingleSample.inputs.plumbing.json#L49) `gs://...G96830.NA12878.hg38.reference.fingerprint.vcf.gz `for `fingerprint_genotypes_file`. However the fingerprint files are specific to the input ubam being processed. From a user perspective they would see these files as something that doesn't need to be changed and will run the workflow as is with their own sample and come across an error with the CheckFingerPrinting task.
**Request**
Add a note in the Readme to indicate they will need to either replace the json configurations with their own fingerprinting file or remove the file as it is optional. (I'm not sure what they are losing if they don't provide the file)

**Comment by kbergin** [comment]
Thanks for pointing that out, Beri. @gbggrant and @ekiernan thoughts on this input example? We have test inputs folder that has to have that file as an input to properly test the pipeline. But this folder is the input_example, do we want to maintain separate input examples vs test input examples? Is documentation updates all we want here or do we want to remove that file as an input in the input example?

**Comment by ekiernan** [comment]
@kbergin Yes, I think we had plans to clean up the example inputs folder: https://broadinstitute.atlassian.net/jira/software/projects/GL/boards/528?selectedIssue=GL-1525

Then we can't point users to the example inputs and add a clarification about the Fingerprint input in the WGS Overview in the WARP docs.

**Comment by kbergin** [comment]
Great, thank you for the link. I'll get that prioritized.

**Comment by gbggrant** [comment]
Hi @ekiernan have the example inputs been cleaned up / clarified?

**Comment by ekiernan** [comment]
We've added additional clarification about the fingerprint files: https://broadinstitute.github.io/warp/docs/Pipelines/Whole_Genome_Germline_Single_Sample_Pipeline/README.
