### ISSUE TITLE
Invalid type coercion in JointGenotyping.wdl

### ISSUE THREAD

**Issue by jdidion** [broadinstitute/warp#341]
At line 368, an `Array[String]` is assigned to a variable of type `Array[Int]`:

`Array[Int] fingerprinting_indices = GetFingerprintingIntervalIndices.indices_to_fingerprint`

According to the WDL specification, this is an invalid type coercion. Instead, in the `GetFingerprintingIntervalIndices` task, change the output type of `indices_to_fingerprint` from `Array[String]` to `Array[Int]`. Immediate coercion from the `Array[String]` return value of `read_lines()` to another type `Array[P]` (where `P` is a primitive type) is allowed as a special case.

**Comment by kbergin** [comment]
Hi John,

Thank you for calling this to our attention. We agree it's a bit unclear to do this and that the spec says it's invalid. It's interesting because it works in the environments we run in, and the wdl validation and linters we use (womtool and miniwdl) haven't chirped up about it! 

Is this invalid type coercion preventing you from using this WDL in another environment?

**Comment by jdidion** [comment]
The WDL specification (all versions, but see 1.1 for greatest clarity) states which automatic type coercions are valid. `String` -> `Int` is not one of them. I believe miniwdl allows this because Cromwell does, and people expect it to work everywhere if it works in Cromwell. I am hoping we can shift to adhering the spec rather than to Cromwell behavior.

Regarding your second question - `wdlTools` does not allow this coercion, and so it prevents the workflow being compiled with `dxCompiler`.

**Comment by kbergin** [comment]
Thank you for clarifying that! We will plan on updating this in the pipeline.

**Comment by gbggrant** [comment]
@kbergin do we have a ticket for this in the backlog? If so can we close out this issue?

**Comment by kbergin** [comment]
GL-1609. But I usually leave the issues open and just label as 'ticket-made' since our backlog isn't public.

**Comment by kevinpalis** [comment]
dxWDL is now on maintenance mode. Closing this issue. Please create a new issue if the problem persists.
