### ISSUE TITLE
Non-public intervals files referenced in joint-genotyping json file

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/warp#342]
In this json file: `warp/pipelines/broad/dna_seq/germline/joint_genotyping/by_chromosome/wgs/JointGenotypingByChromosomePartOne.template.input.json`

The following file appears private not accessible for non broad users:

`"JointGenotypingByChromosomePartOne.unpadded_intervals_file": "gs://broad-gotc-prod-storage/joint_genotyping/intervals/hg38.even.handcurated.20k.{CHROMOSOME}.intervals",`

unlike the other files referred in the json file
`JointGenotypingByChromosomePartOne.ref_fasta": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta"
`

Could that be moved to a public bucket?

**Comment by kbergin** [comment]
Hello @jjfarrell ! I am so sorry I missed your issue until now.

We will file an issue to update those template inputs to point to public files, but in the meantime I am attaching the interval lists to this issue as that's the fastest way to get them to you! 

Generally I wanted to mention that we are going to be releasing a new update to the Joint Calling pipeline this fall that should make it more scalable. When that is released, we are considering deprecating the by_chromosome pipeline. If you're willing to share, are you running your joint callset on GCP? About how many samples and is it exomes or genomes?

[jg_interval_lists.zip](https://github.com/broadinstitute/warp/files/6896915/jg_interval_lists.zip)

**Comment by jjfarrell** [comment]
Thanks for updating that. 

We are running the joint-call set on a linux HPCC system that uses sge. The initial set of crams is 2000 samples and eventually 4000 crams.   

In the new version to be released, what will be making it more scalable? From our runs, the memory requirements for even  one chromosome (80-100 GB) seems excessive  when just running it on a very small interval. This  makes it difficult to run many jobs in parallel. Is that addressed in the next version?

**Comment by kbergin** [comment]
Ah, the new version will be taking advantage of Big Query to help scale and reduce the cost of joint calling in the cloud. Unfortunately I don't think any of the changes in that pipeline will help with running it on SGE. 

It looks like you're already aiming to, but just reinforcing that the by chromosome pipeline is worth trying for SGE to see if it helps.
