### ISSUE TITLE
GroupQCs command not found

### ISSUE THREAD

**Issue by varikmp** [broadinstitute/warp#370]
Hello team,

I have been trying to execute the script https://github.com/broadinstitute/warp/blob/develop/pipelines/skylab/smartseq2_single_sample/SmartSeq2SingleSample.wdl that is depending on another one https://github.com/broadinstitute/warp/blob/develop/tasks/skylab/LoomUtils.wdl. Unfortunately, I could not find the command GroupQCs in the file on line 248. Is there any documentation for that command I can follow up?

Thank you so much.

Best regards,

**Comment by jessicaway** [comment]
Hello @varikmp,

Thanks for reaching out, we are happy to help!  

The `GroupQCs` command is an sctools command. The definition can be found in the sctools repo [(linked here)](https://github.com/HumanCellAtlas/sctools/blob/65ac1a00146950cf789cfcd9aed8632b6725c879/src/sctools/platform.py#L519). 

If you can tell us a little more about how you are running the pipeline, we might be able to offer some additional assistance.

**Comment by varikmp** [comment]
Hello @jessicaway,

Thank you so much for your respond.

I had sctools installed, and I can now use the GroupQCs command.

I am currently using docker-based commands to execute the pipeline above.
