### ISSUE TITLE
option to set read_length in WholeGenomeGermlineSingleSample.wdl

### ISSUE THREAD

**Issue by zihhuafang** [broadinstitute/warp#404]
Is it possible to set read_length by the user as it is currently set at 250, which may not always be true depending on the generated data? 

We are running the workflow on Terra.
Thanks!

**Comment by ekiernan** [comment]
Hi! This parameter has to do with the sizing of arrays in CollectWgsMetrics.  As long as it is equal to or larger than the actual read lengths, the program will run fine.  If the actual read lengths are larger than this is set to, that can result in an exception being thrown (particularly if the actual read lengths are much longer than this value). We're working on adding this to our documentation.

**Comment by kbergin** [comment]
@zihhuafang please reopen this issue if this hasn't answered your question!
