### ISSUE TITLE
Optimus pipeline RunEmptyDrops error (sn-rna mode)

### ISSUE THREAD

**Issue by jingwen** [broadinstitute/warp#405]
Hi, I ran Optimus pipeline with sn_rna mode and got an error at RunEmptyDrops step.
> Error:  'x' must be an array of at least two dimensions 

I checked the sparse_counts.npz, sparse_counts_row_index.npy and sparse_counts_column_index.npy. They look very similar to other scRNA-seq output. Do you know what could drive this error? Is it because of the sinlge-nucleus mode? Thanks!

**Comment by kbergin** [comment]
@kishorikonwar could you take a look at this question? 

@jingwen I will mention we just recently released a new version of Optimus that you could try and see if you continue to get this error.

**Comment by gbggrant** [comment]
Hi @jingwen - we believe this is a known issue with samples with low read counts. We are working on a way to bypass those samples in the pipeline.

**Comment by gbggrant** [comment]
@jingwen a fix for this should be implemented in the pipeline at this point. I'm going to close this issue, please feel free top open a new one if you have further problems.
