### ISSUE TITLE
VerifyIDIntensity scores

### ISSUE THREAD

**Issue by diegomscoelho** [broadinstitute/warp#407]
Hi,

I'm facing some issues with VerifyIDIntensity using [IlluminaArray](https://github.com/broadinstitute/warp/blob/develop/pipelines/broad/genotyping/illumina/IlluminaGenotypingArray.wdl) WDL.

I didn't find any reference to score numbers but I understood that (%Mix) range from 0 to 1. Anyway, my results are between 0.05 to 0.1. We have more than 500 samples with this results (multiple experiments). When we run those samples in batches (48 to 96 joined), we get contamination super low (less than 0.001).

Example:

Per sample using broad WDL:
ID	%Mix		LLK		LLK0	
-----------------------------------------------------------------
0	0.0647098	229726	230666

Running in batches:
ID	%Mix		LLK		LLK0	
-----------------------------------------------------------------
0	0.0472843	2.69374e+06	3.54958e+06
1	0.00126394	-1.20963e+06	-1.20888e+06
2	8.17127e-07	-1.0635e+06	-1.0635e+06
3	8.17127e-07	-947901	-947902
... (more 92 samples)

Do you guys know a threshold running per sample? Is normal to have this %Mix values?

Best, Diego

**Comment by kbergin** [comment]
@gbggrant Could you take a look at this question?

**Comment by gbggrant** [comment]
Hi @diegomscoelho the short answer is that we don't use VerifyIDIntensity.  We found the values generated by it in single sample mode to be inaccurate.  We had some plans to use it in multi-sample mode (by generating a panel of normals to co-run with the sample to be tested) but have instead switched to [BAFRegress](https://genome.sph.umich.edu/wiki/BAFRegress) which does a far better job of estimating contamination.  Unfortunately, to use BAFRegress you need a per-chip-type minor allele frequency file for which we have only one (for the GDA array).

Honestly, we really should deprecate VerifyIDIntensity and remove it from the pipeline.

**Comment by kbergin** [comment]
We will remove from the pipeline in the future and I think the main question in this ticket has been addressed so I will be closing. Feel free to reopen if not!
