### ISSUE TITLE
the use of licence

### ISSUE THREAD

**Issue by lipidong** [broadinstitute/warp#413]
https://github.com/broadinstitute/warp/blob/39b91307f31b29eb08970172e64d22390920edc0/tasks/broad/Alignment.wdl#L71

This script using the bwa command is released under the WDL source code license (BSD-3), while bwa is released under the GPL v3.

I am confused the use of license, so is this a reasonable way ?

**Comment by kbergin** [comment]
Hello @lipidong -

Generally the GPL licenses are viral, ie if you bundle a GPL library into your code, your code becomes GPL too. But in the case of WDL, BWA is not truly a part of the script code and we don't distribute BWA itself, it's just an external call to a BWA executable. So the virality of the license doesn't apply.

Feel free to reopen this if you have further questions!
