### ISSUE TITLE
womtool fails on graph building

### ISSUE THREAD

**Issue by EugeneEA** [broadinstitute/warp#438]
Hi, I'm trying to build a DAG with the following comand:
java_11 -jar ~/bin/womtool-68.1.jar graph UnmappedBamToAlignedBam.wdl | dot -Tpdf  > UnmappedBamToAlignedBam.wdl.pdf
(from the warp/pipelines/broad/dna_seq/germline/single_sample/wgs)
and it fail with the error:
`Exception in thread "main" java.util.NoSuchElementException: key not found: ScatterVariableNode(WomIdentifier(LocalName(unmapped_bam),FullyQualifiedName(unmapped_bam)),PlainAnonymousExpress
ionNode(WomIdentifier(LocalName(unmapped_bam),FullyQualifiedName(unmapped_bam)), etc ...
`

Best, Eugene

**Comment by pshapiro4broad** [comment]
This sounds like a bug in `womtool graph`, I would report it at https://github.com/broadinstitute/cromwell/issues

I would try using `miniwdl` to generate a graph for your WDL. https://miniwdl.readthedocs.io/en/latest/wdlviz.html
