### ISSUE TITLE
IlluminaGenotypingArray.wdl - support for GRCh38?

### ISSUE THREAD

**Issue by kew24** [broadinstitute/warp#439]
Hi,

Our lab has been using IlluminaGenotypingArray.wdl, and we were wondering if there are any plans to allow for GRCh38 in the future. We have successfully used the wdl with GRCh37, but because picard's GtcToVcf (used in IlluminaGenotypingArrayTasks.wdl) doesn't support GRCh38, we are unable to run this workflow with GRCh38. Will this be a feature in future versions of the wdl? 

Thanks!

**Comment by gbggrant** [comment]
Hi @kew24 we definitely want to support GRCh38.  We'll try to get this prioritized in the next quarter.  I need to look in more detail at what needs to be updated in GtcToVcf (hopefully it's minor) - but if you have interest in taking on this work (and contributing a PR to the Picard repo) we would welcome it.

Thanks.

George

**Comment by gbggrant** [comment]
Closing for now, as a ticket for this has been made. Waiting to prioritize the work.
