### ISSUE TITLE
Errors while running ExomeGermlineSingleSample_v2.4.6 locally

### ISSUE THREAD

**Issue by lim20120041** [broadinstitute/warp#472]
Dear all, I am running this ExomeGermlineSingleSample_v2.4.6 WDL workflow with Cromwell locally. I have set backend: "Local" in options.json file. It didn't work for me, I am still getting the "unrecognized runtime attribute keys". Then, I tried to add LocalExample backend config. However, I am still getting some errors as below,

1. Docker lookup failed (I downloaded all the docker images as per the links provided in the WDL workflow scripts)
2. Unrecognized runtime attributes
3. Localization via hard link has failed > operation not permitted

If you are seeing an error, please provide(REQUIRED) :
**a) GATK version used:** us.gcr.io/broad-gatk/gatk:4.1.8.0 (as indicated in ExomeGermlineSingleSample_v2.4.6 wdl workflow script)

**b) Exact command used:** 

```
java \
-Dconfig.file=cromwell.conf \
-jar cromwell-69.jar \
run \
-o /data/my-prototype/gatk-workflows/exome-germline-single-sample-v2.4.6/ExomeGermlineSingleSample_v2.4.6.options.json \
-i /data/my-prototype/gatk-workflows/exome-germline-single-sample-v2.4.6/ExomeGermlineSingleSample_v2.4.6_inputs.json \
--imports /data/my-prototype/gatk-workflows/exome-germline-single-sample-v2.4.6/ExomeGermlineSingleSample_v2.4.6.zip \
/data/my-prototype/gatk-workflows/exome-germline-single-sample-v2.4.6/ExomeGermlineSingleSample_v2.4.6.wdl \
&> /data/my-prototype/gatk-workflows/inputs/workflow_LWBCAW18101701_output9.log & disown
```

**c) Entire error log:**
https://drive.google.com/drive/folders/1E4LCJCiXv_bJkLuVJfonBtrqUmIJd2Qz?usp=sharing (workflow log, config and options.json files)

`[[38;5;220mwarn[0m] Local [[38;5;2mbcff1315[0m]: Key/s [preemptible, disks, cpu, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.`
 
`[[38;5;220mwarn[0m] BackendPreparationActor_for_bcff1315:ExomeGermlineSingleSample.GenerateSubsettedContaminationResources:-1:1 [[38;5;2mbcff1315[0m]: Docker lookup failed`

```
java.lang.Exception: Failed to get docker hash for us.gcr.io/broad-gotc-prod/bedtools:2.27.1 Timeout while looking up hash of us.gcr.io/broad-gotc-prod/bedtools:2.27.1.

Ensure that docker is running correctly.
```
 
`[[38;5;220mwarn[0m] Localization via hard link has failed: /data/my-prototype/gatk-workflows/cromwell-executions/ExomeGermlineSingleSample/bcff1315-f130-45be-8c3d-1e57e0a98852/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6158698a-1fe2-4ddb-8c3d-eeaaa63392dd/call-CheckContamination/inputs/-1986997635/LWBCAW18101701.aligned.duplicate_marked.sorted.bam -> /data/my-prototype/gatk-workflows/cromwell-executions/ExomeGermlineSingleSample/bcff1315-f130-45be-8c3d-1e57e0a98852/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/6158698a-1fe2-4ddb-8c3d-eeaaa63392dd/call-SortSampleBam/execution/LWBCAW18101701.aligned.duplicate_marked.sorted.bam: Operation not permitted`

Seeking help on how to configure the backend for running locally? Thank you!

**Comment by kbergin** [comment]
I expect that early next year we will have made some updates to the pipelines to better accommodate running on prem. We are also working with Intel to publish an inputs json specifically optimized for on prem compute (on intel), a script to modify the pipeline to extract out anything that cannot be used on prem, like the runtime attributes you mentioned, and documentation on how to use the pipeline in that environment. 

In the meantime, I think the best resource we have would be this [fork of the whole genome pipeline] (https://github.com/broadinstitute/warp/compare/develop...priyankasebastian:test_WholeGenomeGermlineSingleSample_v2.3.3) (which is very similar to the exome pipeline) that was modified by Intel to run on prem. 

I apologize that the pipeline doesn't work in your environment out of the box today. I would be happy to reach out and let you know when we publish those materials so you can try it out.

**Comment by gbggrant** [comment]
@kbergin do you want to keep this issue open until the work is done?

**Comment by kbergin** [comment]
We are still working on some of these changes, slow moving alongside other priorities. @lim20120041 I will write on our ticket for this to notify you when it's done, but we can close this one for now.
