### ISSUE TITLE
GVCF files from Dragen as input for JointGenotyping workflow

### ISSUE THREAD

**Issue by wdesouza** [broadinstitute/warp#475]
I'd like to know if the JointGenotyping workflow (v1.5.1) supports GVCF files generated by Illumina Dragen v3.8+. Is there any modification to do on variant recalibration tasks?

**Comment by ldgauthier** [comment]
We've been running the JointGenotyping workflow on DRAGEN GVCFs after running them through the ReblockGVCF workflow, which modifies the GQ and QUAL, effectively turning off some of the DRAGEN-specific features by ignoring the genotype posteriors.  Initial tests ran successfully with good accuracy on NA12878, but the MQ distribution is different for the DRAGEN mapper compared with BWA.  I expect the workflow will run, but it's still on our agenda to further optimize it for DRAGEN data.

**Comment by gbggrant** [comment]
@wdesouza I'm going to close this issue as it sounds like you have the initial information you need to proceed. Please open another issue if you have any problems.
