### ISSUE TITLE
Container for DropletUtils using 'root' folder as PATH for scripts

### ISSUE THREAD

**Issue by BioNica** [broadinstitute/warp#772]
Dear developers,

we are trying to run Optimus locally on a shared environment (HPC, non-root user)
In this environment we use **Singularity** instead of Docker to run the containers.
For most containers called by the Optimus pipeline, the local images are working fine.
We just were not able to port the DropletUtils container called by RunEmptyDrops.wdl

The reason appears to be the placement of the scripts at the `root` directory during container build

https://github.com/broadinstitute/warp/tree/develop/dockers/skylab/emptydrops
https://github.com/broadinstitute/warp/blob/develop/dockers/skylab/emptydrops/Dockerfile

`WORKDIR /root/ `

[...]

```
# Add EmptyDrop scripts
RUN mkdir /root/tools
COPY emptyDropsWrapper ./tools/emptyDropsWrapper
COPY npz2rds ./tools/npz2rds

ENV PATH="/root/tools/emptyDropsWrapper/:/root/tools/npz2rds/:$PATH" 

```

For the compatibility with Singularity and shared environment, would it be possible to change the scripts location to `/opt `or some place accessible by non-root users?

Also changing the working directory to the default local user entry point would avoid permission issues.

Thank you!

**Comment by kevinpalis** [comment]
This is done and merged via PR: https://github.com/broadinstitute/warp/pull/904
