### ISSUE TITLE
ImportGVCFs call of JointGenotyping.wdl does not have an access to input gvcfs 

### ISSUE THREAD

**Issue by EugeneEA** [broadinstitute/warp#782]
Hi, I'm struggling to launch JointGenotyping.wdl (on a local server with slurm backend), constantly having an error 
`A USER ERROR has occurred: Failed to create reader from file:///cromwell-executions/JointGenotyping/373a1fd9-f69c-4a0c-9bec-c656aa066295/call-ImportGVCFs/shard-6/execution/NNR00008092.15628.g.vcf.gz`

Which I think is understandable - because in the workflow we are passing `File sample_name_map` in the input of ImportGVCFs, but the cromwell know nothing of where the files listed in this file are on my server when it launch the docker container with the volume mounted like this:
```
docker run \
  --cidfile /home-local/warp_dev/pipelines/broad/dna_seq/germline/joint_genotyping/cromwell-executions/JointGenotyping/373a1fd9-f69c-4a0c-9bec-c656aa066295/call-ImportGVCFs/shard-
6/execution/docker_cid \
  -i \
   \
  --entrypoint /bin/bash \
  -v /home-local/warp_dev/pipelines/broad/dna_seq/germline/joint_genotyping/cromwell-executions/JointGenotyping/373a1fd9-f69c-4a0c-9bec-c656aa066295/call-ImportGVCFs/shard-6:/crom
well-executions/JointGenotyping/373a1fd9-f69c-4a0c-9bec-c656aa066295/call-ImportGVCFs/shard-6:delegated \
  us.gcr.io/broad-gatk/gatk@sha256:18146e79d06787483310e5de666502090a480e10ac0fad06a36a5e7a5c9bb1dc /cromwell-executions/JointGenotyping/373a1fd9-f69c-4a0c-9bec-c656aa066295/call-ImportGVCF
s/shard-6/execution/script

```

and later `GenomicsDBImport` clearly fail to find files listed in the map file in the container because they are not in the `shard-6/import/...` folder
Is it some sort of bug or I do not understand something here?

An advice will be appreciated, best, Eugene

**Comment by EugeneEA** [comment]
PS - I fixed it by changing `--sample-name-map ~{sample_name_map} \` to `-V ~{sep=" -V " gvcfs} \`
and passing     `Array[File] gvcfs` and `Array[File] gvcfs_idx` to `ImportGVCFs`. But I honestly do not understand how the original code could possibly works

**Comment by jessicaway** [comment]
Hi @EugeneEA thanks for bringing this issue to our attention. We do not currently support OnPrem implementations of our pipelines (unfortunately). This is useful insight though. 

I am closing this issue for now, since you were able to resolve the problem
