### ISSUE TITLE
latest ultima genomics gatk jar file

### ISSUE THREAD

**Issue by williambrandler** [broadinstitute/warp#809]
Hi, how do I get access to the latest ultima genomics specific gatk jar file?

**Comment by jessicaway** [comment]
@meganshand  are you able to help @williambrandler with this request?

**Comment by meganshand** [comment]
Sorry for the delayed response @williambrandler. We haven't yet released the Ultima Genomics specific version of GATK, although this should be coming in the next few weeks. In the meantime, the master version of GATK includes all of the Ultima specific changes. You can either build GATK from the source code here: [github.com/broadinstitute/gatk](https://github.com/broadinstitute/gatk) or I believe there are nightly docker images hosted here: https://hub.docker.com/r/broadinstitute/gatk-nightly/ Any of the recent docker image tags there should have the Ultima specific version.

Let me know if neither of those options work for you and I can copy the built jar somewhere for you. Thanks!

**Comment by williambrandler** [comment]
ah great, thanks @meganshand 

please comment again on this thread when the ultima enabled version of the gatk is released!

For now please send the built jar to me over email (you have my contact details!)

Thanks,

William

**Comment by meganshand** [comment]
The latest release of GATK includes Ultima support: https://github.com/broadinstitute/gatk/releases/tag/4.3.0.0
