### ISSUE TITLE
Reference FASTA choice for DRAGMAP `MergeBamAlignment`

### ISSUE THREAD

**Issue by vladsavelyev** [broadinstitute/warp#871]
I wonder if it is chosen deliberately to pass the non-masked reference FASTA into `MergeBamAlignment` for DRAGMAP alignments:

`gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta`

Instead of passing the one from `dragmap_reference`:

`gs://gcp-public-data--broad-references/hg38/v0/dragen_reference/Homo_sapiens_assembly38_masked.fasta`

https://github.com/broadinstitute/warp/blob/a3b438422691f447032038be52c74639dafe914f/tasks/broad/DragmapAlignment.wdl#L70

We have CRAMs that were aligned outside of WARP with DRAGMAP using the same masked reference, and they end up incompatible with WARP-aligned CRAMs because of different contig md5 sums in the headers. Even though I believe the actual alignment should be the same.

**Comment by lgruen** [comment]
@michaelgatzen Do you remember the rationale for this (as this was added in #197)? Was this approach chosen to increase the compatibility for downstream processes?

**Comment by michaelgatzen** [comment]
The idea is that you can run the entire pipeline with the masked reference, i.e. pass the masked versions of the files to the `reference_fasta` input to the workspace, not just to the `dragmap_reference`. This will avoid any incompatibilities within the pipeline itself, but @lgruen is right, this might require a re-header in case any downstream tasks require exact matching of the md5 sums.

**Comment by vladsavelyev** [comment]
Thank you for your response and the explanation! It caused a bigger internal discussion in our centre about the rationale of changing the header of CRAM files, and I forgot to get back to this issue. Can be closed now :)
