### ISSUE TITLE
Received error when running Exome-Analysis-Pipeline on Terra

### ISSUE THREAD

**Issue by beneopp** [broadinstitute/warp#909]
Hi,

I got the following error and not sure what it means and what to do:

Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: unable to start unit "docker-5138ea370ebc8e0ffbaacfa269d11d72ee0402090b2898f41b9cabf1bdbfb287.scope" (properties [{Name:Description Value:"libcontainer container 5138ea370ebc8e0ffbaacfa269d11d72ee0402090b2898f41b9cabf1bdbfb287"} {Name:Slice Value:"system.slice"} {Name:Delegate Value:true} {Name:PIDs Value:@au [4209]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): read unix @->/run/dbus/system_bus_socket: EOF: unknown

Here is the whole log file:

2023/01/27 01:13:37 Starting container setup.
2023/01/27 01:13:39 Done container setup.
2023/01/27 01:13:43 Starting localization.
2023/01/27 01:13:59 Localization script execution started...
2023/01/27 01:13:59 Localizing input gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-HaplotypeCallerGATK4/shard-31/script -> /cromwell_root/script
2023/01/27 01:14:02 Localizing input gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-ScatterIntervalList/glob-cb4648beeaff920acb03de7603c06f98/39scattered.interval_list -> /cromwell_root/fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-ScatterIntervalList/glob-cb4648beeaff920acb03de7603c06f98/39scattered.interval_list
2023/01/27 01:14:03 Localizing input gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/d5330d10-6d85-42ab-b17e-b99dada80b57/call-GatherBamFiles/JB-0144-N-01v2.bai -> /cromwell_root/fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/d5330d10-6d85-42ab-b17e-b99dada80b57/call-GatherBamFiles/JB-0144-N-01v2.bai
2023/01/27 01:14:07 Localizing input gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta -> /cromwell_root/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
2023/01/27 01:14:54 Localizing input gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai -> /cromwell_root/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai
2023/01/27 01:14:54 Localizing input gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dict -> /cromwell_root/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dict
Copying gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai...
/ [0 files][ 0.0 B/157.2 KiB] / [1 files][157.2 KiB/157.2 KiB] Copying gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dict...
/ [1 files][157.2 KiB/725.2 KiB] / [2 files][725.2 KiB/725.2 KiB]
Operation completed over 2 objects/725.2 KiB.
2023/01/27 01:14:57 Localization script execution complete.
2023/01/27 01:15:03 Done localization.
2023/01/27 01:15:04 Running user action: docker run -v /mnt/local-disk:/cromwell_root -v /mnt/d-1b2e5749db4b0a6439c4895809508e1e:/mnt/af7b5955462dc70f18fa6a82eae18e22:ro --entrypoint=/bin/bash us.gcr.io/broad-gatk/gatk@sha256:21c3cb43b7d11891ed4b63cc7274f20187f00387cfaa0433b3e7991b5be34dbe /cromwell_root/script
Total available memory: 7954 MB
Memory reserved for Java: 6930 MB
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.fd37d811
01:15:18.011 WARN GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default
01:15:18.018 WARN GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardHCAnnotation) is enabled for this tool by default
01:15:18.155 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
01:15:18.970 INFO HaplotypeCaller - ------------------------------------------------------------
01:15:18.971 INFO HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.2.6.1
01:15:18.971 INFO HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
01:15:18.971 INFO HaplotypeCaller - Executing as root@bc1e35f6577f on Linux v5.15.65+ amd64
01:15:18.972 INFO HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
01:15:18.972 INFO HaplotypeCaller - Start Date/Time: January 27, 2023 1:15:18 AM GMT
01:15:18.973 INFO HaplotypeCaller - ------------------------------------------------------------
01:15:18.973 INFO HaplotypeCaller - ------------------------------------------------------------
01:15:18.974 INFO HaplotypeCaller - HTSJDK Version: 2.24.1
01:15:18.975 INFO HaplotypeCaller - Picard Version: 2.27.1
01:15:18.975 INFO HaplotypeCaller - Built for Spark Version: 2.4.5
01:15:18.975 INFO HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
01:15:18.975 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
01:15:18.975 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
01:15:18.975 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
01:15:18.976 INFO HaplotypeCaller - Deflater: IntelDeflater
01:15:18.976 INFO HaplotypeCaller - Inflater: IntelInflater
01:15:18.976 INFO HaplotypeCaller - GCS max retries/reopens: 20
01:15:18.976 INFO HaplotypeCaller - Requester pays: disabled
01:15:18.976 INFO HaplotypeCaller - Initializing engine
01:15:22.577 INFO FeatureManager - Using codec IntervalListCodec to read file file:///cromwell_root/fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-ScatterIntervalList/glob-cb4648beeaff920acb03de7603c06f98/39scattered.interval_list
01:15:23.001 INFO IntervalArgumentCollection - Processing 4419456 bp from intervals
01:15:23.060 INFO HaplotypeCaller - Done initializing engine
01:15:23.065 INFO HaplotypeCallerEngine - Tool is in reference confidence mode and the annotation, the following changes will be made to any specified annotations: 'StrandBiasBySample' will be enabled. 'ChromosomeCounts', 'FisherStrand', 'StrandOddsRatio' and 'QualByDepth' annotations have been disabled
01:15:23.215 INFO HaplotypeCallerEngine - Standard Emitting and Calling confidence set to 0.0 for reference-model confidence output
01:15:23.216 INFO HaplotypeCallerEngine - All sites annotated with PLs forced to true for reference-model confidence output
01:15:23.242 INFO NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/gatk/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_utils.so
01:15:23.266 INFO NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/gatk/gatk-package-4.2.6.1-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
01:15:23.378 INFO IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
01:15:23.379 INFO IntelPairHmm - Available threads: 2
01:15:23.379 INFO IntelPairHmm - Requested threads: 4
01:15:23.379 WARN IntelPairHmm - Using 2 available threads, but 4 were requested
01:15:23.379 INFO PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
01:15:23.557 INFO ProgressMeter - Starting traversal
01:15:23.557 INFO ProgressMeter - Current Locus Elapsed Minutes Regions Processed Regions/Minute
01:15:27.194 WARN InbreedingCoeff - InbreedingCoeff will not be calculated at position chr16:50675812 and possibly subsequent; at least 10 samples must have called genotypes
01:15:33.866 INFO ProgressMeter - chr16:51140886 0.2 300 1746.0
01:15:43.873 INFO ProgressMeter - chr16:53993262 0.3 1230 3632.6
01:15:56.656 INFO ProgressMeter - chr16:55833026 0.6 1960 3553.0
01:16:06.953 INFO ProgressMeter - chr16:56904414 0.7 2740 3788.4
01:16:16.958 INFO ProgressMeter - chr16:57621244 0.9 3550 3988.7
01:16:26.983 INFO ProgressMeter - chr16:58678481 1.1 4610 4361.0
01:16:36.991 INFO ProgressMeter - chr16:67538528 1.2 6570 5368.2
01:16:47.017 INFO ProgressMeter - chr16:69349373 1.4 8220 5909.4
01:16:57.093 INFO ProgressMeter - chr16:70497426 1.6 9220 5914.3
01:17:07.150 INFO ProgressMeter - chr16:71954284 1.7 10510 6087.3
01:17:17.884 INFO ProgressMeter - chr16:74410824 1.9 11480 6024.9
01:17:27.959 INFO ProgressMeter - chr16:78056275 2.1 13020 6279.6
01:17:38.006 INFO ProgressMeter - chr16:82056603 2.2 14630 6528.9
01:17:48.103 INFO ProgressMeter - chr16:84880762 2.4 16010 6645.6
01:17:58.119 INFO ProgressMeter - chr16:88534277 2.6 17830 6921.5
01:18:08.240 INFO ProgressMeter - chr16:89280538 2.7 18890 6882.3
01:18:18.647 INFO ProgressMeter - chr16:89762114 2.9 19660 6737.1
01:18:28.656 INFO ProgressMeter - chr17:510428 3.1 20660 6697.0
01:18:38.854 INFO ProgressMeter - chr17:1747512 3.3 21860 6715.9
01:18:41.878 INFO HaplotypeCaller - 143690 read(s) filtered by: MappingQualityReadFilter
0 read(s) filtered by: MappingQualityAvailableReadFilter
0 read(s) filtered by: MappedReadFilter
0 read(s) filtered by: NotSecondaryAlignmentReadFilter
527000 read(s) filtered by: NotDuplicateReadFilter
0 read(s) filtered by: PassesVendorQualityCheckReadFilter
0 read(s) filtered by: NonZeroReferenceLengthAlignmentReadFilter
0 read(s) filtered by: GoodCigarReadFilter
0 read(s) filtered by: WellformedReadFilter
670690 total reads filtered
01:18:41.878 INFO ProgressMeter - chr17:2232530 3.3 22234 6726.7
01:18:41.878 INFO ProgressMeter - Traversal complete. Processed 22234 total regions in 3.3 minutes.
01:18:41.892 INFO VectorLoglessPairHMM - Time spent in setup for JNI call : 0.15113531000000002
01:18:41.892 INFO PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 22.712422133
01:18:41.893 INFO SmithWatermanAligner - Total compute time in java Smith-Waterman : 21.44 sec
01:18:41.894 INFO HaplotypeCaller - Shutting down engine
[January 27, 2023 1:18:41 AM GMT] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 3.40 minutes.
Runtime.totalMemory()=7214727168
Using GATK jar /gatk/gatk-package-4.2.6.1-local.jar
Running:
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx6930m -Xms6930m -XX:GCTimeLimit=50 -XX:GCHeapFreeLimit=10 -jar /gatk/gatk-package-4.2.6.1-local.jar HaplotypeCaller -R /cromwell_root/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta -I gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-UnmappedBamToAlignedBam/UnmappedBamToAlignedBam/d5330d10-6d85-42ab-b17e-b99dada80b57/call-GatherBamFiles/JB-0144-N-01v2.bam -L /cromwell_root/fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-ScatterIntervalList/glob-cb4648beeaff920acb03de7603c06f98/39scattered.interval_list -O JB-0144-N-01v2.g.vcf.gz -contamination 0.0012743986666666667 -G StandardAnnotation -G StandardHCAnnotation -G AS_StandardAnnotation -GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 50 -GQB 60 -GQB 70 -GQB 80 -GQB 90 -ERC GVCF
2023/01/27 01:18:45 Starting delocalization.
2023/01/27 01:18:46 Delocalization script execution started...
2023/01/27 01:18:46 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-HaplotypeCallerGATK4/shard-31/memory_retry_rc
2023/01/27 01:18:49 Delocalizing output /cromwell_root/rc -> gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-HaplotypeCallerGATK4/shard-31/rc
2023/01/27 01:18:50 Delocalizing output /cromwell_root/stdout -> gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-HaplotypeCallerGATK4/shard-31/stdout
2023/01/27 01:18:52 Delocalizing output /cromwell_root/stderr -> gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-HaplotypeCallerGATK4/shard-31/stderr
2023/01/27 01:18:54 Delocalizing output /cromwell_root/JB-0144-N-01v2.bamout.bam -> gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-HaplotypeCallerGATK4/shard-31/JB-0144-N-01v2.bamout.bam
2023/01/27 01:18:55 Delocalizing output /cromwell_root/JB-0144-N-01v2.g.vcf.gz.tbi -> gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-HaplotypeCallerGATK4/shard-31/JB-0144-N-01v2.g.vcf.gz.tbi
2023/01/27 01:18:57 Delocalizing output /cromwell_root/JB-0144-N-01v2.g.vcf.gz -> gs://fc-c041d11f-01e7-44b7-b124-840098e27b01/submissions/1b03f4ae-f956-4a67-96b6-7bb9be49b446/ExomeGermlineSingleSample/9f04fb8d-5c19-49a9-83dc-6ea52e628005/call-BamToGvcf/VariantCalling/583b95a9-5732-4677-93f9-a7627b13e1c0/call-HaplotypeCallerGATK4/shard-31/JB-0144-N-01v2.g.vcf.gz
2023/01/27 01:18:58 Delocalization script execution complete.
2023/01/27 01:18:59 Done delocalization.
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: unable to apply cgroup configuration: unable to start unit "docker-5138ea370ebc8e0ffbaacfa269d11d72ee0402090b2898f41b9cabf1bdbfb287.scope" (properties [{Name:Description Value:"libcontainer container 5138ea370ebc8e0ffbaacfa269d11d72ee0402090b2898f41b9cabf1bdbfb287"} {Name:Slice Value:"system.slice"} {Name:Delegate Value:true} {Name:PIDs Value:@au [4209]} {Name:MemoryAccounting Value:true} {Name:CPUAccounting Value:true} {Name:IOAccounting Value:true} {Name:TasksAccounting Value:true} {Name:DefaultDependencies Value:false}]): read unix @->/run/dbus/system_bus_socket: EOF: unknown

**Comment by kevinpalis** [comment]
@beneopp - This looks like a Terra issue. Please reach out to Terra support if this is still happening: https://support.terra.bio/hc/en-us/requests/new
Thanks!
