### ISSUE TITLE
Biotypes for slide-seq

### ISSUE THREAD

**Issue by kzb193** [broadinstitute/warp#979]
Hello, 

I am interested in obtaining bam file from a pair of slide-seq V2 fastq files, and I am new to this domain.
Can you please provide some leads on how to prepare/obtain the Biotypes.tsv file for human genome (hg19)?

**Comment by guille-ucl** [comment]
I think you need to build a tsv with two columns (file attached, might have to change extension from txt to tsv):
-One with the biotypes found here: https://www.gencodegenes.org/pages/biotypes.html
-Other with "Y" or "N" (unquoted) depending on the biotypes you want to include

I have deduced this based on the little that the documentation says and examining some error messages when trying to run the BuildIndices pipeline
[Biotypes.txt](https://github.com/broadinstitute/warp/files/11898061/Biotypes.txt)

**Comment by nikellepetrillo** [comment]
Hi @kzb193, @guille-ucl gave a great explanation. I have added the Biotypes.tsv we use in our Multiome pipeline for your reference. You can modify your allowable biotypes according to your GTF file. 

```# List of gene_type or transcript_type in GENCODE and Ensembl GTF file ( see: https://www.gencodegenes.org/pages/biotypes.html)
# The first column is the gene_type or transcript_type attribute of the gtf and
# the second column is a boolean (Y,N) if it is set to Y (or y), that biotype will be included in the gtf file.
IG_C_gene	 Y
IG_D_gene	 Y
IG_J_gene	 Y
IG_LV_gene	 Y
IG_V_gene	 Y
TR_C_gene	 Y
TR_J_gene	 Y
TR_V_gene	 Y
TR_D_gene	 Y
IG_pseudogene	 N
IG_C_pseudogene	 Y
IG_J_pseudogene	 Y
IG_V_pseudogene	 Y
TR_V_pseudogene	 Y
TR_J_pseudogene	 Y
Mt_rRNA	 N
Mt_tRNA	 N
miRNA	 N
misc_RNA	 N
rRNA	 N
scRNA	 N
snRNA	 N
snoRNA	 N
ribozyme	 N
sRNA	 N
scaRNA	 N
lncRNA	 Y
Mt_tRNA_pseudogene	 N
tRNA_pseudogene	 N
snoRNA_pseudogene	 N
snRNA_pseudogene	 N
scRNA_pseudogene	 N
rRNA_pseudogene	 N
misc_RNA_pseudogene	 N
miRNA_pseudogene	 N
TEC	 N
nonsense_mediated_decay	 N
non_stop_decay	 N
retained_intron	 N
protein_coding	 Y
processed_transcript	 N
non_coding	 N
ambiguous_orf	 N
sense_intronic	 N
sense_overlapping	 N
antisense/antisense_RNA	 N
known_ncrna	 N
pseudogene	 N
processed_pseudogene	 N
polymorphic_pseudogene	 N
retrotransposed	 N
transcribed_processed_pseudogene	 N
transcribed_unprocessed_pseudogene	 N
transcribed_unitary_pseudogene	 N
translated_processed_pseudogene	 N
translated_unprocessed_pseudogene	 N
unitary_pseudogene	 N
unprocessed_pseudogene	 N
artifact	 N
lincRNA	 N
macro_lncRNA	 N
3prime_overlapping_ncRNA	 N
disrupted_domain	 N
vaultRNA/vault_RNA	 N
bidirectional_promoter_lncRNA	 N
```

**Comment by jessicaway** [comment]
@kayleemathews @ekiernan We should update the documentation to point to the public version of the biotypes file

**Comment by ekiernan** [comment]
Public version of biotypes TSV is now linked in documentation in this PR" https://github.com/broadinstitute/warp/pull/1074

When the PR merges, you will find the link in the Slide-seq Overview: https://broadinstitute.github.io/warp/docs/Pipelines/SlideSeq_Pipeline/README
