### ISSUE TITLE
imputation HG38 support

### ISSUE THREAD

**Issue by zhaohongqiangsoliva** [broadinstitute/warp#981]
Dear sir
for each example test is HG19 version ,i try to change  HG38 reference ,but not work ,please tould me how to do for HG38

**Comment by nikellepetrillo** [comment]
Hi @zhaohongqiangsoliva, what kind of error are you seeing? Do you have a stacktrace we can take a look at?

Thanks!
Nikelle

**Comment by zhaohongqiangsoliva** [comment]
oh,sorry
I forgot to check the question of the issue,
I found a reference about IMPUTATION HG19 in the warp pipeline, but HG38 didn't, and I tried to use my own HG38 reference
It has errors related to headers, roughly due to the presence of a lot  of minssing sites,
I understand that it's because I'm not handling the Reference correctly.
Do you have a suggested reference handling process here?
Or best practices
Error message is likely:
```
  "workflowRoot": "/disk/pipeline/cromwell/cromwell-executions/Imputation/c6b32d3c-35e9-4b52-ba62-b6fd99f8a8e1",
3715   │   "actualWorkflowLanguage": "WDL",
3716   │   "status": "Failed",
3717   │   "failures": [
3718   │     {
3719   │       "causedBy": [
3720   │         {
3721   │           "causedBy": [
3722   │             {
3723   │               "causedBy": [],
3724   │               "message": "Bad output 'CalculateChromosomeLength.chrom_length': Failed to read_int(\"/disk/pipeline/cromwell/cromwell-executions/Imputation/c6b32d3c-35e9-4b52-ba62-b6fd99f8a8
       │ e1/call-CalculateChromosomeLength/shard-1/execution/stdout\") (reason 1 of 1): For input string: \"\""
3725   │             }
3726   │           ],
3727   │           "message": "Failed to evaluate job outputs"
3728   │         },
3729   │         {
3730   │           "causedBy": [
3731   │             {
3732   │               "causedBy": [],
3733   │               "message": "Bad output 'CalculateChromosomeLength.chrom_length': Failed to read_int(\"/disk/pipeline/cromwell/cromwell-executions/Imputation/c6b32d3c-35e9-4b52-ba62-b6fd99f8a8
       │ e1/call-CalculateChromosomeLength/shard-0/execution/stdout\") (reason 1 of 1): For input string: \"\""
3734   │             }
3735   │           ],

```

**Comment by aawdeh** [comment]
Closing this issue as HG38 is currently not supported. Were working with other teams to see how you can build the files needed to make it work.
