### ISSUE TITLE
Support for 'prefer not to answer' 

### ISSUE THREAD

**Issue by mfisher29** [broadinstitute/warp#988]
Hi warp team,

I came across this issue when running a sample through Arrays.wdl that resulted in this error:

```
[Thu May 18 17:27:10 UTC 2023] edu.mit.broad.picard.arrays.UpdateChipWellBarcodeIndex done. Elapsed time: 0.04 minutes.
Runtime.totalMemory()=2027421696
Exception in thread "main" picard.PicardException: Unrecognized gender string: Prefer not to answer
```

Full error here:
https://job-manager.dsde-prod.broadinstitute.org/jobs/698a046b-cef8-4c79-93f4-e1f1239fffb8

Looks like this sample is not able to move forward given this is an unrecognized gender string. Can we edit this? Or is a different, but similar meaning string supported?

thank you!
Marissa

**Comment by mfisher29** [comment]
Update:
arrays pipeline supports:
```
Female
Male
Unknown
NotReported
```

but R4 supports :
```
·       Female
·       Male
·       Intersex
·       Prefer not to answer
```

**Comment by kevinpalis** [comment]
Hi @mfisher29 - we're looking into this. We'll keep you posted! Thanks!

**Comment by jessicaway** [comment]
We are not planning to update the pipeline at this time. Please reopen if this continues to be an issue
